"""扩展 messages 表中的 AI 元数据

Revision ID: 88d0b09ff954
Revises: 23347f72c50a
Create Date: 2026-08-30 17:27:06.837649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d0b09ff954'
down_revision: Union[str, Sequence[str], None] = '23347f72c50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.add_column('messages', sa.Column('reasoning_content', sa.Text(), nullable=True, comment='模型思维链思考内容，DeepSeek等模型输出的内部思考文本'))
    op.add_column('messages', sa.Column('token_usage', sa.JSON(), nullable=True, comment='response_metadata内token_usage，token消耗明细字典'))
    op.add_column('messages', sa.Column('usage_metadata', sa.JSON(), nullable=True, comment='langchain usage_metadata，输入输出、缓存读写token统计信息'))
    op.add_column('messages', sa.Column('response_metadata', sa.JSON(), nullable=True, comment='AIMessage.response_metadata，模型返回完整响应元数据'))
    op.add_column('messages', sa.Column('additional_kwargs', sa.JSON(), nullable=True, comment='additional_kwargs，厂商扩展字段：reasoning_content、refusal、搜索信息等'))
    op.add_column('messages', sa.Column('tool_calls', sa.JSON(), nullable=True, comment='tool_calls数组，AI发起的工具调用请求列表'))
    op.add_column('messages', sa.Column('invalid_tool_calls', sa.JSON(), nullable=True, comment='invalid_tool_calls，解析异常、格式错误的工具调用'))
    op.add_column('messages', sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称，例如 deepseek‑v4‑flash，冗余快捷字段'))
    op.add_column('messages', sa.Column('finish_reason', sa.String(length=50), nullable=True, comment='会话结束原因：stop / length / tool_calls'))
    op.add_column('messages', sa.Column('message_id', sa.String(length=100), nullable=True, comment='大模型返回的消息唯一id'))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息文本内容；仅工具调用无输出时可为null',
               existing_comment='消息文本内容；工具调用消息可存null',
               existing_nullable=True)
    op.alter_column('messages', 'token_count',
               existing_type=sa.INTEGER(),
               comment='本条消息总token简易统计，用于计费展示，可为null',
               existing_comment='本条消息token消耗数量，用于统计计费，可为null',
               existing_nullable=True)
    op.drop_column('messages', 'meta_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('meta_data', sa.TEXT(), autoincrement=False, nullable=True, comment='扩展元数据，保存JSON字符串；工具调用、trace附加信息，业务自行序列化解析'))
    op.alter_column('messages', 'token_count',
               existing_type=sa.INTEGER(),
               comment='本条消息token消耗数量，用于统计计费，可为null',
               existing_comment='本条消息总token简易统计，用于计费展示，可为null',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息文本内容；工具调用消息可存null',
               existing_comment='消息文本内容；仅工具调用无输出时可为null',
               existing_nullable=True)
    op.drop_column('messages', 'message_id')
    op.drop_column('messages', 'finish_reason')
    op.drop_column('messages', 'model_name')
    op.drop_column('messages', 'invalid_tool_calls')
    op.drop_column('messages', 'tool_calls')
    op.drop_column('messages', 'additional_kwargs')
    op.drop_column('messages', 'response_metadata')
    op.drop_column('messages', 'usage_metadata')
    op.drop_column('messages', 'token_usage')
    op.drop_column('messages', 'reasoning_content')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
